# Generated by Django 5.0.2 on 2024-02-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(), null=True),
        ),
    ]
