# Generated by Django 5.0.2 on 2024-02-26 07:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_product_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_with_discount',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال /غیر فعال'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='حذف شده / نشده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url_title',
            field=models.CharField(default=1, max_length=32, verbose_name='عنوان url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت نهایی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=1, verbose_name='حذف شده / نشده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=32, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=32, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product_module.brand', verbose_name='برند'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال /غیر فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='توضیحات خلاصه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=32, verbose_name='عنوان محصول '),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='عنوان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag', to='product_module.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='product_module.category'),
        ),
    ]
