# Generated by Django 5.0.2 on 2024-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(null=True, verbose_name='قیمت نهایی'),
        ),
    ]
