# Generated by Django 5.0.2 on 2024-03-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.PositiveSmallIntegerField(verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
