# Generated by Django 5.0.2 on 2024-03-05 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(11)], verbose_name='تلفن همراه'),
        ),
    ]
