# Generated by Django 5.0.2 on 2024-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
