# Generated by Django 5.0.2 on 2024-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='درباره شخص'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to='images/profile', verbose_name='عکس پروفایل'),
        ),
    ]
