# Generated by Django 5.0.2 on 2024-03-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=330, verbose_name='آدرس')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تلقن')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='فکس')),
                ('site_name', models.CharField(max_length=330, verbose_name='اسم سایت')),
                ('site_url', models.CharField(max_length=32, verbose_name='آدرس سایت')),
                ('copy_right', models.TextField(verbose_name='کپی رایت')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('site_logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوگوی سایت')),
                ('is_main_site_setting', models.BooleanField(default=False, verbose_name='تظیم به عوان اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
