# Generated by Django 5.0.2 on 2024-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sittings', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=330, verbose_name='عنوان لینک')),
                ('url', models.URLField(max_length=300, verbose_name='لینک ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='عکس ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال | غیر فعال ')),
            ],
            options={
                'verbose_name': 'تنظیمات اسلاید',
                'verbose_name_plural': 'تنظیمات اسلایدر',
            },
        ),
    ]
