# Generated by Django 5.0.2 on 2024-03-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sittings', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320, verbose_name='عنوان')),
                ('url', models.URLField(max_length=320, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزئیات محصول'), ('about_us', 'صفحه درباره ما')], max_length=320, verbose_name='محل قرارگیری')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'تبلیغات',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
