# Generated by Django 5.0.2 on 2024-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('message', models.TextField(verbose_name='پیام کاربر ')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پیام ادمین')),
                ('is_read_by_admin', models.BooleanField(verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'لیست ارتباط با ما',
            },
        ),
    ]
